### ISSUE TITLE
Unlock B1-3

### ISSUE THREAD

**Issue by radityabh** [langit7/Bolt-arion-pl100#3]
Akses DM command lewat telnet gmana bro?

**Comment by langit7** [comment]
dari telnet ketik lted_cli kemudian ketik arm1log 2

**Comment by radityabh** [comment]
> dari telnet ketik lted_cli kemudian ketik arm1log 2

![image](https://user-images.githubusercontent.com/15983827/162162966-456aadef-40d3-4dc6-aae6-447c72fc5130.png)
oke, bisa. cara nambah b3 gman ya?

**Comment by langit7** [comment]
Konsepnya sama dengan yg b1
````
1. Add vport
USAGE: nvm bcfgw 0 <port> <pport> 
nvm bcfgw 0 8 4
nvm bcfgw 0 9 5
2. Add band port
nvm bcfgw 1 8 3
nvm bcfgw 1 9 3
3. save config
nvm bcfgsv 1
4. Restart modem 
reboot
5. Add scan band band 40 ,1 dan 3
nvm bcfgw 49 0 40 1 3
atau rrc capw 4 3 1 3 40  
6. save config
nvm bcfgsv 1
7. Restart modem 
reboot`
```

**Comment by radityabh** [comment]
> Konsepnya sama dengan yg b1

tp gak konek ya? atau ada  yg di set lagih?

**Comment by langit7** [comment]
> tp gak konek ya? atau ada yg di set lagih?
Harus setting  radio calibration dll, ini yg belum selesai
bisa liat contohnya untuk band 40
`rfm rfcal 2
`

**Comment by radityabh** [comment]
> > Harus setting  radio calibration dll, ini yg belum selesai
> > bisa liat contohnya untuk band 40
> > `rfm rfcal 2 `

oke siap, dtunggu next step nyah. thanks

**Comment by SandyMaull** [comment]
permisi suhu pgn nanya..
ane coba eksekusi rfm rfcal 2 di telnet hasilnya bikin binggung..
klo boleh tau harus pelajarin apa biar ngerti ini? ane baru terjun ke dunia ngoprek2 ginian hehe...
siapa tau bisa bantu nantinya klo sudah ngerti wkwk.

![Screenshot 2022-04-21 181123](https://user-images.githubusercontent.com/14269978/164944346-f7222aaf-d7b6-4112-ba80-59d81bd3a01d.jpg)
